# ===============================
# Task Service (Production)
# ===============================
spring.application.name=task-service
server.port=8080

# ===============================
# MongoDB Atlas (Render)
# ===============================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# ===============================
# Logging
# ===============================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

# ===============================
# Jackson (Date handling)
# ===============================
spring.jackson.serialization.write-dates-as-timestamps=false